# Generated by Django 4.0.2 on 2022-04-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='organization',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
