# Generated by Django 4.0.2 on 2022-04-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_userprofile_firstname_userprofile_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
    ]
