# Generated by Django 4.0.2 on 2022-04-07 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_profile_birthday_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 7, 8, 11, 44, 585369, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='None', max_length=1, null=True),
        ),
    ]
