# Generated by Django 4.0.2 on 2022-04-07 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_profile_birthday_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 4, 7, 11, 57, 0, 916292, tzinfo=utc), null=True),
        ),
    ]
