# Generated by Django 4.0.2 on 2022-04-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
