# Generated by Django 4.0.4 on 2022-08-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_tags_rename_question_folder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='question_text',
            new_name='folder_text',
        ),
    ]
