# Generated by Django 4.0.4 on 2022-08-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_rename_question_text_folder_folder_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='tags',
        ),
    ]
