# Generated by Django 4.1 on 2022-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_remove_choice_votes_choice_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='source',
        ),
        migrations.AddField(
            model_name='choice',
            name='folders',
            field=models.ManyToManyField(null=True, to='polls.folder'),
        ),
        migrations.AddField(
            model_name='choice',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='tags',
        ),
        migrations.AddField(
            model_name='choice',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='polls.tags'),
        ),
    ]
