# Generated by Django 4.1 on 2022-09-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_choice_folder_remove_choice_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='folders',
            new_name='folders_contained_in',
        ),
    ]
