# Generated by Django 4.0.4 on 2022-09-08 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_folder_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
