# Generated by Django 4.0.4 on 2022-09-08 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_folder_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 8)),
        ),
    ]
