# Generated by Django 4.0.4 on 2022-09-08 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_alter_folder_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='pub_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
    ]
