# Generated by Django 4.0.4 on 2022-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_folder_pub_date_only_folder_pub_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
