# Generated by Django 4.0.4 on 2022-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_remove_folder_folders_in_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='date_published',
        ),
        migrations.AddField(
            model_name='choice',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
