# Generated by Django 4.0.4 on 2022-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_remove_choice_date_published_choice_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='author',
            field=models.TextField(blank=True, default=''),
        ),
    ]
