# Generated by Django 4.0.4 on 2022-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_choice_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='folders_contained_in',
            field=models.ManyToManyField(to='polls.folder'),
        ),
    ]
