# Generated by Django 4.0.4 on 2022-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_alter_choice_folders_contained_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='choice',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='source_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='tags',
            field=models.ManyToManyField(null=True, to='polls.tags'),
        ),
    ]
