# Generated by Django 4.1 on 2022-09-09 01:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0042_remove_folder_pub_time_alter_folder_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 1, 51, 43, 103402)),
        ),
    ]
