# Generated by Django 4.0.4 on 2022-09-10 02:51

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0043_folder_creator_alter_folder_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='folders',
            field=models.ManyToManyField(null=True, to='polls.folder'),
        ),
        migrations.AddField(
            model_name='tags',
            name='sources',
            field=models.ManyToManyField(null=True, to='polls.source'),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='creator',
        ),
        migrations.AddField(
            model_name='folder',
            name='creator',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 10, 51, 13, 240084)),
        ),
    ]
