# Generated by Django 4.0.4 on 2022-09-10 02:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0044_remove_source_tags_tags_folders_tags_sources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='creator',
        ),
        migrations.AddField(
            model_name='folder',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 10, 54, 28, 596110)),
        ),
    ]
