# Generated by Django 4.0.4 on 2022-09-10 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_alter_folder_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 11, 26, 1, 821611)),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
