# Generated by Django 4.0.4 on 2022-09-10 03:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0047_folder_tags_alter_folder_pub_date_delete_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 11, 31, 38, 318621)),
        ),
    ]
