# Generated by Django 4.0.4 on 2022-09-10 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_tag_alter_folder_pub_date_remove_folder_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 21, 43, 51, 96670)),
        ),
    ]
