# Generated by Django 4.0.4 on 2022-10-09 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_alter_folder_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 22, 17, 6, 792682)),
        ),
    ]
